export const motionConfig = {
  media: {
    compactQuery: "(max-width: 860px)",
  },
  hero: {
    scrollLengthVh: 100,
    mobileScrollLengthVh: 100,
    scrub: 1.35,
    letterStagger: 0.035,
    labelStagger: 0.05,
    introDuration: 0.7,
    wordExitDuration: 0.25,
    wordExitOffset: 100,
    subtitXPercentDesktop: 120,
    subtitXPercentMobile: 30,
    brainDesktopLeft: "39%",
    brainDesktopTop: "55%",
    brainMobileLeft: "50%",
    brainMobileTop: "42%",
    brainTravelScale: 1.16,
  },
  highlight: {
    autoplayMs: 5000,
    clipDuration: 1,
    clipEase: "cubic-bezier(0.76, 0, 0.24, 1)",
    scrollStepBias: 0.0001,
  },
  solution: {
    autoplayMs: 3000,
    slideSpeedMs: 700,
    scrollStepBias: 0.0001,
  },
  data: {
    countUpDurationMs: 1300,
    countUpDelayMs: 120,
  },
  reveal: {
    y: 8,
    blur: 0,
    duration: 0.28,
    ease: "none",
    start: "top bottom+=780",
    end: "top 98%",
    scrub: true,
  },
  scene: {
    entryStart: "top 108%",
    entryEnd: "top 86%",
    exitStart: "bottom 82%",
    exitEnd: "bottom 18%",
    y: 12,
    blur: 0,
    parallaxY: -16,
    stagger: 0.055,
  },
  globalYear: {
    from: 1985,
    to: 2026,
  },
};
